# Generated by Django 3.2.1 on 2024-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('normal', 'Normal User')], default='normal', max_length=10),
        ),
    ]
