# Generated by Django 3.2.1 on 2024-09-17 20:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('license_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('seat_number', models.IntegerField()),
                ('status', models.CharField(choices=[('on_going', 'On going'), ('completed', 'Completed')], max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('on_going', 'On going'), ('completed', 'Completed')], max_length=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buscompany',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='company',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='route',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='number',
            new_name='car_number',
        ),
        migrations.RenameField(
            model_name='busroute',
            old_name='origin',
            new_name='station',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='busstation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.AddField(
            model_name='bus',
            name='air_conditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='bus',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol')], default='diesel', max_length=6),
        ),
        migrations.AddField(
            model_name='bus',
            name='gear_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=9),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_number',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.busstation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busroute',
            name='region',
            field=models.CharField(blank=True, choices=[('Upper West Region', 'Upper West Region'), ('Upper East Region', 'Upper East Region'), ('North East Region', 'North East Region'), ('Northern Region', 'Northern Region'), ('Savannah Region', 'Savannah Region'), ('Bono East Region', 'Bono East Region'), ('Brong Ahafo Region', 'Brong Ahafo Region'), ('Oti Region', 'Oti Region'), ('Volta Region', 'Volta Region'), ('Eastern Region', 'Eastern Region'), ('Ashanti Region', 'Ashanti Region'), ('Ahafo Region', 'Ahafo Region'), ('Western North Region', 'Western North Region'), ('Western Region', 'Western Region'), ('Central Region', 'Central Region'), ('Greater Accra Region', 'Greater Accra Region')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route_name',
            field=models.CharField(default='Accra', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstation',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstation',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 17, 20, 49, 42, 322347, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstation',
            name='company_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='busstation',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 17, 20, 50, 14, 63511, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BusCompany',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.AddField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.bus'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.busroute'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.driver'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.busstation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.schedule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busstation',
            name='working_days',
            field=models.ManyToManyField(related_name='station', to='base.WorkingDay'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.reservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.schedule'),
            preserve_default=False,
        ),
    ]
