# Generated by Django 3.2.1 on 2024-09-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240917_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.busstation'),
            preserve_default=False,
        ),
    ]
