# Generated by Django 3.2.1 on 2024-09-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_driver_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstation',
            name='working_days',
        ),
        migrations.AddField(
            model_name='busstation',
            name='working_days',
            field=models.CharField(default='Mon', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
    ]
