# Generated by Django 3.2.1 on 2024-09-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20240918_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='air_conditioner',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
