# Generated by Django 3.2.1 on 2024-09-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_schedule_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='working_days',
            field=models.JSONField(),
        ),
    ]
