# Generated by Django 3.2.1 on 2024-09-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_busstation_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='phone_number',
            field=models.CharField(default='0552238893', max_length=15),
            preserve_default=False,
        ),
    ]
