# Generated by Django 3.2.1 on 2024-09-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20240923_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
