# Generated by Django 3.2.1 on 2024-09-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20240923_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reference',
            new_name='full_name',
        ),
    ]
