# Generated by Django 3.2.1 on 2024-09-24 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_busrental_rentalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('pickup', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Upper West Region', 'Upper West Region'), ('Upper East Region', 'Upper East Region'), ('North East Region', 'North East Region'), ('Northern Region', 'Northern Region'), ('Savannah Region', 'Savannah Region'), ('Bono East Region', 'Bono East Region'), ('Brong Ahafo Region', 'Brong Ahafo Region'), ('Oti Region', 'Oti Region'), ('Volta Region', 'Volta Region'), ('Eastern Region', 'Eastern Region'), ('Ashanti Region', 'Ashanti Region'), ('Ahafo Region', 'Ahafo Region'), ('Western North Region', 'Western North Region'), ('Western Region', 'Western Region'), ('Central Region', 'Central Region'), ('Greater Accra Region', 'Greater Accra Region')], max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.busrental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
