# Generated by Django 3.2.1 on 2024-09-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_busrental_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bus'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.busroute'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.busstation'),
        ),
    ]
