# Generated by Django 3.2.1 on 2024-09-27 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rentalrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrental',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 27, 10, 1, 59, 252524, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 27, 10, 2, 17, 775834, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
